### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by dirk-thomas** [WPI-RAIL/interactive_world#1]
The code uses headers from `std_srvs` (https://github.com/WPI-RAIL/interactive_world/blob/a5a27a3d52d9a692a41acc05d73defe713e3e92b/spatial_world_model/include/spatial_world_model/Tracker.h#L7) but the package.xml does not contain a dependency on `std_srvs`.

**Comment by rctoris** [comment]
Whoops, fixed in https://github.com/WPI-RAIL/interactive_world/commit/1405de275d6b5a14385970a5738765aa07f7ac4e
